### ISSUE TITLE
Scrolling fast between months

### ISSUE THREAD

**Issue by rosothefox** [Mozharovsky/CVCalendar#55]
When I keep scrolling right quickly, instead of going to previous months it goes to new months (the direction is opposite). Same thing happens in the other direction..

**Comment by Mozharovsky** [comment]
Hello @rosothefox, 

This issue is fixed in the pre-release version. You can get the most recent code in the [develop branch](https://github.com/Mozharovsky/CVCalendar/tree/develop). 

Please close the issue if it works for you. Otherwise let me know!

Regards, 
Eugene

**Comment by rosothefox** [comment]
Hey, thanks so much for your response and the good work!

It works much better now, but still not perfect - because when I scroll fast sometimes it just bounces instead of moving smoothly to the next month. I guess because the screen is not ready yet.

**Comment by Mozharovsky** [comment]
Hello @rosothefox, 

CVCalendar in the develop branch simply rejects loading next/previous month if the current loading operation is not over. As a result you won't get unnecessary processor cycles and memory waste. If you're familiar with Google Calendar then the calendar they're using does ultimately the same thing. So this way should work. 

If you're not good with how it is let me know what would you like to see instead. 

Regards, 
Eugene

**Comment by rosothefox** [comment]
Thanks again for your kind reply, I understand how it works.. I think the ideal behavior of the scrolling should be as if it never loads any screens - imagine that it would load 10 screens in the stack instead of 3, and every time he user scroll it will update the 10 screens of the stack. That way the user will be able to scroll freely and never reach a situation where he scrolls and there's no screen ready yet.

I know this is probably a lot of work, but this will be the ultimate behavior for the calendar. I truly appreciate your attention to the users and desire to make the calendar the best one available today, thanks!

**Comment by Mozharovsky** [comment]
Hello @rosothefox, 

Loading 10 month views would take too much memory which is unnecessary for most of cases. It's unlikely a user to scroll more then 2 months but still possible. I think I can create a cache scrolling which will be pretty much optimised and in the same time will solve this issue. 

It's now a part of 1.1.0 release so you can expect the feature this weekend. 

Regards, 
Eugene

**Comment by rosothefox** [comment]
Cool! Thanks a lot!

I said 10 but it can also be 5, I don't know about memory but most calendars load few months in advance

**Comment by rosothefox** [comment]
Hey! any news when 1.1.0 release will be out?

**Comment by Mozharovsky** [comment]
Hello @rosothefox, 

Hopefully I have less work this week and it might come out in the following week or two. 

Regards, 
Eugene

**Comment by rosothefox** [comment]
Ok mate all the new features look great expecting it impatiently :) thanks!
