### ISSUE TITLE
My Calendar View Didn't Expand its Height When That Month Needs An Extra Row [Help Needed]

### ISSUE THREAD

**Issue by shan199105** [Mozharovsky/CVCalendar#97]
![ios simulator - iphone 6 - iphone 6 - ios 8 4 12h141 ios simulator today at 2 30 25 am](https://cloud.githubusercontent.com/assets/2152195/8760609/f6317258-2cf4-11e5-83db-b8ae09807700.png)

![ios simulator - iphone 6 - iphone 6 - ios 8 4 12h141 ios simulator today at 2 30 51 am](https://cloud.githubusercontent.com/assets/2152195/8760610/0385c5b2-2cf5-11e5-9ee4-4dcbdbf9a58b.png)

When I switch from July to August, it didn't add an extra row which it suppose to. However, in the demo app, it behaves normally. I wonder where I made a mistake for that. Please give me some hint and I will really appreciate.

Here is how I write the code. I have the override viewDidLayoutSubviews() of course. I didn't use storyboard at all. Everything I created is programmatically. The way I create the calendarView is I give it a frame size and init it using CVCalendarView(frame: frame) and assign the calendarDelegate.

I have tried to solve this bug for a long time. Any help will be appreciated. Thank you so much for your time.

**Comment by thomasbaldwin** [comment]
The way it resizes you're calendar is based off the height constraints. You need to set a height constraint on your CalendarView, and it should fix the problem

**Comment by shan199105** [comment]
I really appreciate your hint. However, I didn't solve the problem . I am sorry that I have to bother you again. 

I fixed my code and add constraints instead of giving the calendarView a fixed height. But that still didn't work. It doesn't affect anything at all.  Here is how I init the calendarView
````
func calendarViewSetup () {
    self.mainCalendarView = CVCalendarView()
    self.mainCalendarView.setTranslatesAutoresizingMaskIntoConstraints(false)
   
    self.mainCalendarView.calendarDelegate = calendarDelegate
    self.mainCalendarView.backgroundColor = UIColor.whiteColor()
    self.addSubview(self.mainCalendarView)
    
    // add constraint
    let horizontalConstraint = NSLayoutConstraint(
      item: self.mainCalendarView,
      attribute: NSLayoutAttribute.CenterX,
      relatedBy: NSLayoutRelation.Equal,
      toItem: self,
      attribute: NSLayoutAttribute.CenterX,
      multiplier: 1,
      constant: 0)
    
    let verticalConstraint = NSLayoutConstraint(
      item: self.mainCalendarView,
      attribute: NSLayoutAttribute.CenterY,
      relatedBy: NSLayoutRelation.Equal,
      toItem: self,
      attribute: NSLayoutAttribute.CenterY,
      multiplier: 1,
      constant: 0)
    
    let widthConstrant = NSLayoutConstraint(
      item: self.mainCalendarView,
      attribute: NSLayoutAttribute.Width,
      relatedBy: NSLayoutRelation.Equal,
      toItem: nil,
      attribute: NSLayoutAttribute.NotAnAttribute,
      multiplier: 1,
      constant: calendarView_width)
    
    let heightConstrant = NSLayoutConstraint(
      item: self.mainCalendarView,
      attribute: NSLayoutAttribute.Height,
      relatedBy: NSLayoutRelation.Equal,
      toItem: nil,
      attribute: NSLayoutAttribute.NotAnAttribute,
      multiplier: 1,
      constant: calendarView_height)
    
    self.addConstraints([horizontalConstraint, verticalConstraint, widthConstrant, heightConstrant])
  }
````

Also in ViewController, I have 
````
  override func viewDidLayoutSubviews() {
    super.viewDidLayoutSubviews()

    // calView is the whole view
    // mainCalendarView is the CVCalendarView
    self.calView.mainCalendarView.commitCalendarViewUpdate()
    self.calView.mainCalendarView.changeMode(.MonthView)
    self.calView.calendarLabelView.commitMenuViewUpdate()
  }
````

Thank you very much for your time. Looking forward to your reply.

**Comment by Mozharovsky** [comment]
Hello @shan199105, 

Please check out  [develop](https://github.com/Mozharovsky/CVCalendar/tree/develop) branch along with issued #101 #104. It seems the height calculation doesn't work properly for your case but a newer version should help. 

If it doesn't please let me know!

Regards, 
Eugene

**Comment by shan199105** [comment]
Thanks Problem Solved
